# -*- coding: utf-8 -*-
"""circle-animation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sOHflU7U_5cTtedJRBUs8rcTueaLL61y

**This animation program have 2 versions and I used circle shape to draw these shapes.**

**Version 1:** In this version I have used circle shape to draw simple 1 layer mandala shape. You can drwa multi-layer mandala shape using this code.
"""

import turtle
import math

# Set up the turtle screen
turtle.bgcolor("black")
screen = turtle.Screen()
screen.title("Simple Mandala")
squary = turtle.Turtle()
squary.speed(0)
squary.color("red")
squary.width(2)

# Function to draw a single circle
def draw_circle(radius):
    squary.circle(radius)

# Function to draw the mandala pattern
def draw_mandala(num_circles, max_radius):
    angle = 360 / num_circles
    for _ in range(num_circles):
        draw_circle(max_radius)
        squary.right(angle)

# Set the position and size of the mandala
squary.penup()
squary.goto(0, -50)  # Adjust the position as needed
squary.pendown()

# Draw the mandala
num_circles = 12  # Number of circles in the mandala
max_radius = 100  # Maximum radius of the largest circle
draw_mandala(num_circles, max_radius)

# Close the turtle graphics window on click
screen.exitonclick()

"""**Version 2:** after completing the mandala shep in this version I have reverse the output using undo() function to decrease the circles to initial point."""

import turtle

# Set up the turtle screen
turtle.bgcolor("black")
screen = turtle.Screen()
screen.title("Reversing Mandala")
squary = turtle.Turtle()
squary.speed(0)
squary.color("red")
squary.width(2)

# Function to draw a single circle
def draw_circle(radius):
    squary.circle(radius)

# Function to draw the mandala pattern
def draw_mandala(num_circles, max_radius):
    angle = 360 / num_circles
    for _ in range(num_circles):
        draw_circle(max_radius)
        squary.right(angle)

# Set the position and size of the mandala
squary.penup()
squary.goto(0, -50)  # Adjust the position as needed
squary.pendown()

# Draw the mandala
num_circles = 12  # Number of circles in the mandala
max_radius = 100  # Maximum radius of the largest circle
draw_mandala(num_circles, max_radius)

# Reverse the drawing by erasing the circles
for _ in range(num_circles):
    squary.undo()

# Close the turtle graphics window on click
screen.exitonclick()